BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [name] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [gender] BIT NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [birthdate] DATETIME2 NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [birthplace] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [isMotherWorks] BIT NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [motherName] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [currentAddress] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [fatherDeathDate] DATETIME2 NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [joinDate] DATETIME2 NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [motherJob] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [liveWith] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Orphan] ALTER COLUMN [evaluation] FLOAT(53) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
