import Head from 'next/head';
import React from 'react';

function AppHead() {
	return (
		<Head>
			<title>just-next app</title>
			<meta name='description' content='Generated by create next app' />
			<meta name='viewport' content='width=device-width, initial-scale=1' />
			<link rel='icon' href='/favicon.ico' />
		</Head>
	);
}

export default AppHead;
