import Head from 'next/head';
import React from 'react'

function MyHead() {
  return (
			<Head>
				<title>OAMS</title>
				<meta name='description' content='Generated by create next app' />
				{/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
				<meta name='viewport' content='initial-scale=1, width=device-width' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		);
}

export default MyHead