import { Orphan } from '@prisma/client';

export const DefaultOrphanValues = {
	name: '',
	image: null,
	gender: 'male',
	age: 5,
	birthplace: '',
	birthdate: new Date(),
	joinDate: new Date(),
	schoolName: '',
	gradeLevel: null,
	lastYearPercentage: null,
	fatherDeathDate: new Date(),
	fatherWork: '',
	fatherDeathCos: '',
	noOfFamilyMembers: null,
	males: null,
	females: null,
	motherName: '',
	motherStatus: null,
	isMotherWorks: false,
	motherJob: '',
	motherJobPhone: '',
	monthlyIncome: null,
	liveWith: '',
	homeType: '',
	homePhone: '',
	currentAddress: '',
	isSponsored: false,
	foundationName: '',
	foundationAmount: null,
	evaluation: null,
	guardianId: null,
};
export const OrphanAttributes = [
	'id',
	'name',
	'image',
	'gender',
	'age',
	'birthplace',
	'birthdate',
	'joinDate',
	'schoolName',
	'gradeLevel',
	'lastYearPercentage',
	'fatherDeathDate',
	'fatherWork',
	'fatherDeathCos',
	'noOfFamilyMembers',
	'males',
	'females',
	'motherName',
	'motherStatus',
	'isMotherWorks',
	'motherJob',
	'motherJobPhone',
	'monthlyIncome',
	'liveWith',
	'homeType',
	'homePhone',
	'currentAddress',
	'isSponsored',
	'foundationName',
	'foundationAmount',
	'evaluation',
	'guardianId',
];
