export const DefaultOrphan = {
	id: undefined,
	name: '',
	image: null,
	gender: '',
	age: '',
	birthplace: '',
	birthdate: new Date(),
	joinDate: new Date(),
	schoolName: '',
	gradeLevel: '',
	lastYearPercentage: '',
	fatherDeathDate: new Date(),
	fatherWork: '',
	fatherDeathCos: '',
	noOfFamilyMembers: '',
	males: '',
	females: '',
	motherName: '',
	motherStatus: '',
	isMotherWorks: false,
	motherJob: '',
	motherJobPhone: '',
	monthlyIncome: null,
	liveWith: '',
	homeType: '',
	homePhone: '',
	currentAddress: '',
	isSponsored: false,
	foundationName: '',
	foundationAmount: null,
	evaluation: null,
	guardianId: null,
};
export const OrphanAttributes = [
	'id',
	'name',
	'image',
	'gender',
	'age',
	'birthplace',
	'birthdate',
	'joinDate',
	'schoolName',
	'gradeLevel',
	'lastYearPercentage',
	'fatherDeathDate',
	'fatherWork',
	'fatherDeathCos',
	'noOfFamilyMembers',
	'males',
	'females',
	'motherName',
	'motherStatus',
	'isMotherWorks',
	'motherJob',
	'motherJobPhone',
	'monthlyIncome',
	'liveWith',
	'homeType',
	'homePhone',
	'currentAddress',
	'isSponsored',
	'foundationName',
	'foundationAmount',
	'evaluation',
	'guardianId',
];
